sudo: false
language: emacs-lisp

addons:
  apt:
    packages:
    - autogen
    - ca-certificates
    - curl
    - gcc
    - libgmp-dev
    - m4
    - make
    - pkg-config
    - xz-utils

cache:
  directories:
  - $HOME/local

env:
  global:
    - PATH=$HOME/local/bin:$HOME/local/evm/bin:$HOME/local/cask/bin:$PATH
  matrix:
    - EMACS_BINARY=emacs-24.4-travis MAKE_TEST=test
    - EMACS_BINARY=emacs-24.4-travis MAKE_TEST=test-bytecomp
    - EMACS_BINARY=emacs-24.5-travis MAKE_TEST=test
    - EMACS_BINARY=emacs-24.5-travis MAKE_TEST=test-bytecomp
    - EMACS_BINARY=emacs-25.1-travis MAKE_TEST=test
    - EMACS_BINARY=emacs-25.1-travis MAKE_TEST=test-bytecomp
    - EMACS_BINARY=emacs-25.2-travis MAKE_TEST=test
    - EMACS_BINARY=emacs-25.2-travis MAKE_TEST=test-bytecomp
    - EMACS_BINARY=emacs-25.3-travis MAKE_TEST=test
    - EMACS_BINARY=emacs-25.3-travis MAKE_TEST=test-bytecomp
    - EMACS_BINARY=emacs-25.3-travis MAKE_TEST=test-checks
    - EMACS_BINARY=emacs-26-pretest-travis MAKE_TEST=test
    - EMACS_BINARY=emacs-26-pretest-travis MAKE_TEST=test-bytecomp
    - EMACS_BINARY=emacs-26-pretest-travis MAKE_TEST=test-checks
    - EMACS_BINARY=emacs-git-snapshot-travis MAKE_TEST=test
    - EMACS_BINARY=emacs-git-snapshot-travis MAKE_TEST=test-bytecomp
    - EMACS_BINARY=emacs-git-snapshot-travis MAKE_TEST=test-checks

before_script:
  - sh travis-ci/install-gnutls.sh
  - gnutls-cli -v
  - sh travis-ci/install-evm.sh
  - evm install $EMACS_BINARY --use --skip
  - sh travis-ci/install-cask.sh
script:
  - emacs --version
  - make $MAKE_TEST

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/14f0f7b4d5b20a70d032
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
