sudo: true
language: emacs-lisp
env:
  - EMACS_BINARY=emacs-24.3-bin PATH=$HOME/.evm/bin:$PATH MAKE_TEST=test
  - EMACS_BINARY=emacs-24.4-bin PATH=$HOME/.evm/bin:$PATH MAKE_TEST=test
  - EMACS_BINARY=emacs-24.5-bin PATH=$HOME/.evm/bin:$PATH MAKE_TEST=test
  # - EMACS_BINARY=emacs-snapshot MAKE_TEST=test
  - MAKE_TEST=test-bytecomp EMACS_BINARY=emacs-24.5-bin PATH=$HOME/.evm/bin:$PATH
  - MAKE_TEST=test-checks EMACS_BINARY=emacs-24.5-bin PATH=$HOME/.evm/bin:$PATH

before_script:
  - sh vagrant/provision.sh
  - make elpa
script:
  - make $MAKE_TEST

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/14f0f7b4d5b20a70d032
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
