sudo: false
language: emacs-lisp
env:
  - EMACS_BINARY=emacs-24.4-travis MAKE_TEST=test
  - EMACS_BINARY=emacs-24.5-travis MAKE_TEST=test
  - EMACS_BINARY=emacs-25.1-travis MAKE_TEST=test
  - EMACS_BINARY=emacs-git-snapshot-travis MAKE_TEST=test
  - MAKE_TEST=test-bytecomp EMACS_BINARY=emacs-25.1-travis
  - MAKE_TEST=test-checks EMACS_BINARY=emacs-25.1-travis

before_script:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EMACS_BINARY --use --skip
  - make elpa
script:
  - make $MAKE_TEST
matrix:
  - env: EMACS_BINARY=emacs-git-snapshot-travis

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/14f0f7b4d5b20a70d032
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
