# N.B.!! This is the config for the legacy readthedocs site.
# All of the docs pages have been removed from the source, and Page Redirects
# have been setup in the RTD admin console. This means that all cider.readthedocs.io
# links should be redirected to their corresponding docs page at docs.cider.mx.
site_name: "CIDER: The Clojure Interactive Development Environment that Rocks"
repo_url: https://github.com/clojure-emacs/cider
edit_uri: edit/master/legacy-manual/
copyright: "Copyright &copy; 2016-2020 Bozhidar Batsov, Artur Malabarba and CIDER contributors"
docs_dir: legacy-manual
theme: readthedocs
