site_name: "CIDER: The Clojure Interactive Development Environment that Rocks"
repo_url: https://github.com/clojure-emacs/cider
edit_uri: edit/master/doc/
site_favicon: favicon.ico
copyright: "Copyright &copy; 2016-2018 Bozhidar Batsov, Artur Malabarba and CIDER contributors"
docs_dir: doc
pages:
- Home: index.md
- Installation: installation.md
- Up and Running: up_and_running.md
- ClojureScript: clojurescript.md
- Interactive Programming: interactive_programming.md
- Using the REPL: using_the_repl.md
- Managing Connections: managing_connections.md
- Code Completion: code_completion.md
- Navigating Stacktraces: navigating_stacktraces.md
- Running Tests: running_tests.md
- Debugging: debugging.md
- Miscellaneous Features: miscellaneous_features.md
- Configuration: configuration.md
- Indentation Specification: indent_spec.md
- Additional Packages: additional_packages.md
- Caveats: caveats.md
- Troubleshooting: troubleshooting.md
- FAQ: faq.md
- Additional Resources: additional_resources.md
- Hacking on CIDER: hacking_on_cider.md
- About:
    - Team: about/team.md
    - Support: about/support.md
    - Contributing: about/contributing.md
    - Release Policy: about/release_policy.md
    - Changelog: about/changelog.md
    - Logo: about/logo.md
    - License: about/license.md
extra_css:
  - css/extra.css
markdown_extensions:
  - admonition
theme: readthedocs
